language: node_js
node_js:
- '0.11'
sudo: required
notifications:
  email: false
  on_failure: always
  on_success: always
  slack:
    secure: SUj+RjXNc1Y8UunLYcNVf7mR3neoKPmQbzppOgP4of/C4vmLQCaSR0cV80zHTK6r/b+PByc/c3B3XlCzGaCpfMWF5xOaQCfNDTzrkDQMxnr0iHb+PT9DnzFHQk8gCAfDzYa5YofthrtEe1cuumvSn5DNx3PJogLke8CeMVQi+2EwIqJGhF7qo7wUaseHJDDTAwJX945Pjpt6b62DOeu/pHc5OZ+qZaT7sR1TINq+9uHvY87FULV8iZyjjmRWMrQO6sXynoZx7G/6qJzw+G+COLzAs/J7cqGncODYdAv/JMEWds5eAA7Pm1awt1YLZmYc0VN57/TO5++PBJsZ6zbF58OgPkrxnU+evbvrQId1nkw0DJm4OPB/jKIxUpjzfme6e8X1yNQYHYfzscmnps7WdSrU+vDjq14wb2FFCPAHQbQFGvloYYTp77lnv2NnvynWGQqgoysRL7r1tmnN5t3jwOaOgDr0vwNkBQhtaMFRHjPrEWN6/D6ywTGWNCKB5gl4GUGr7zxWko8S9ocs5HxO3RmcaLwAr383ntxqJlVlWyZ0/ZIZygIOxx/oULE58FklOJcP7e8Ifs26nqRDE95TcBfVGnzBaoec300E9YEgaYpwhZnL0wrt0AmZDc/fbAv3tmqLpZSxN72RFY6G9vfolGhun9rumd3C9reEdILNxqI=
branches:
  only:
  - master
before_script:
- chmod +x deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
