language: node_js
node_js:
- '0.11'
sudo: true
notifications:
  email: false
  on_failure: always
  on_success: always
  slack:
    secure: REf7GC5ErsSf8MFii1lxZNeAk5LhQs5VV+VYO0SlXQbM/zRrrZLgLed4cv4jWxxxHWKTSQ8qMRvFxhmamBvUwTLxbZrK5rsxogO7+AtYtUsa3fHH/nEYU7Hgl1D3tuVkO2rxuO9scEUklDf1p4lk7l02daQ9tnAGF2nY/VBNy1lANODc0FckKToh9TOoRnosIVu2Jqc8er7j6TrZsTzuj4nGnQvuqaranEoUTL++9q4e33nghGhCnxV2auV6EWTNv879lK+kU6a9h4OVAp9/G0yoVe0BR0k0sh5uzIdR6JdJifXcs7GLAd+VuxD2WbgdUKkjctoGlcWZeGZzJFW+rXsHt6ihEAk0ffdjfKEe+vSH9FxhkTkxuXUpAQe7ltDpcpTLB+N0qPw0+oO3LP2Nxs32umggl3cJfZ74uObMaxWxC5u1IATfvO8x+3T+j01Oj5p7fxmAjTwo4v7ro+iHtBHvaZVPEIhJ3eAmSrPsYwXzPkbge/bDEcHr8WSAGS8DYSSHgGihYTnA9vjPZqwMBRvFIjpDGUlgVFmfBdCxiqgY7LKhViAnMUKHUiUdaEtVS2Bw0dLj0z9Ip6/Z1VwE2xvTdYehwuSfOb60S+ZlnHC5KTWRE94/dfnJZWKJVFyz0+DpIBUAiat8F3L609SdOTuHFV25J3iajh1FfmXiWcQ=
branches:
  only:
  - master
before_script:
- chmod +x deploy.sh
after_success:
- ./deploy.sh
env:
  global:
  - secure: MZH/AFGY/KBhIbx7lHIGDGnTp+ATwzJAoWEcTj9jZzcmtRcV/1JxmcM3MvMkWVN5pkI9ZcIh0lkje/H6xVTVrohJ97PmnmtZNiW60sLBLmlCZUUgeKriqjezN5m8G79XOb6WjHj/BzV+FWuGYLaPzMVfTEY8XulNu7GjL02hViAOkZmJcKByKxKn9koJzkxgRbjWcdct+SQqt3L1BO+dVIV/bmTGm8LMMVLVzAP+opHVxCo6BbOk+OInijiGd0XsmjSZP+q67joqbtINiP27XLMvn4/NF0Y9j9m9di9ts++qBf9QxuZl/IUU7RZ7EF0P0PaGtTB+IX+jjcxacGUtk359S8znTsXWJg5rjaiFAVvfoOGfb0ehpP8gcp5XlbagdrFBKNwN6udCmcj7TVopQbyUXi0Zj8qxSx63DTcbDKrwZVcKZ8ay90Jq8yOWqbiPWDgCfyMs2c7YJL+YxopLiQNqeTTCYs5AkuspVYNscImmsGmkFeuWxArTwaPL3f8tZjnIbxTnJ+eog8fGYcFir1fCURQ5ljeOfQp81R5nym0wHSDH6ZmaslbNpdNZgg90pcMZo8h2j5z1GzU31b4KZrNtSlnOcL8z7FTQT5y++X9YXxV8DvccpeEviwfF7QOKVX5LA1vDYSGBqNGZw3dGIcZPTv4wUY/6YfmcEmOlkk8=
  - secure: na8CswGySQG99Pq1w8BMyiC5qE2aJZ5Ei331lEhEfFkiqaQZHOcJ+Dix7VmXdsmw/0IGwuXVnVyrnwRYOttuqRGeXMTJZlaf3izBMM4e0fz4qkDBQmyM865QBLEg3Nrvlrsyr0cGSvONFV8AZZbSHCuPhrqXhxwMHpo4SAYt3imffYsa3u4ByVcafSMjYGEmiy5ATSWq50pFfHjtFFHtlM9X+eLOIdRw+zsJeZWkXhWvCtQmBKgbCmmymKBnxevkfLcjhc/xnmS/O1v/6isSDDg/VKYSjHsHh1I8kOpSWvfXsd7GwUgWjs7pDRJV+kwOZOuqhdej+DRzovJs61SbQiIbulYbmhaA0xoeesq6Hs+UkXWbtFG23niGIbzao2erpwhOUb/FqgSvEfvisDL9rLK5NEU0tDOrhuPjwu8sj8RL2AM/4xBT0g13MFQgAZM7PUEhaibW2KvF4MFEd/1kwl2pjfS7D6rDimgQ2B+6aJT/62Qq6PrJuXfh5sG3BrSCOhXSOmtir1enn+lz+da5S++7GPt3/IuohxWHSLWPuu4fmPHn0pVlMV4EFNzTPObdTzP76JQrVMH/C8sqpGO1KGc3NvzBMzENy+BjeVYNJ8AqsTwvYBv4A81275yPskoUNPJXVFzp9qu3hIbUhjyqrz+Mt17eRPoTORuW3qPnDR4=
